#ifndef __COMMON_DEFINITION__
#define __COMMON_DEFINITION__

#define DRIVE_MAX_LEN		32
#define DIR_MAX_LEN			(MAX_PATH*2)
#define TITLE_MAX_LEN		MAX_PATH
#define EXT_MAX_LEN			32
#define NAME_MAX_LEN		(TITLE_MAX_LEN + EXT_MAX_LEN)
#define PATH_MAX_LEN		(DRIVE_MAX_LEN + DIR_MAX_LEN + TITLE_MAX_LEN + EXT_MAX_LEN)
#define CHECK_SUM_MAX_LEN	255
#define TYPE_NAME_MAX_LEN	255
#endif // !__COMMON_DEFINITION__
