#ifndef __COMMON_DEFINITION__
#define __COMMON_DEFINITION__

#define TM_INIT	(WM_USER+1)
#define TM_EXIT	(WM_USER+2)

#define DUPLICATE_CRITERIA_NAME             0x00000001  
#define DUPLICATE_CRITERIA_SIZE             0x00000002  
#define DUPLICATE_CRITERIA_ATTRIBUTES       0x00000004  
#define DUPLICATE_CRITERIA_CONTENT          0x00000010  
#define DUPLICATE_CRITERIA_CREATION_TIME    0x00000020  
#define DUPLICATE_CRITERIA_ACCESS_TIME      0x00000040  
#define DUPLICATE_CRITERIA_WRITE_TIME       0x00000080
#define DUPLICATE_CRITERIA_TYPE				0x00000100  

#define DRIVE_MAX_LEN		32
#define DIR_MAX_LEN			(MAX_PATH*2)
#define TITLE_MAX_LEN		MAX_PATH
#define EXT_MAX_LEN			32
#define NAME_MAX_LEN		(TITLE_MAX_LEN + EXT_MAX_LEN)
#define PATH_MAX_LEN		(DRIVE_MAX_LEN + DIR_MAX_LEN + TITLE_MAX_LEN + EXT_MAX_LEN)
#define CHECK_SUM_MAX_LEN	255
#define TYPE_NAME_MAX_LEN	255


#endif // !__COMMON_DEFINITION__
